[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.28"
evm_version = "cancun"

optimizer = true
optimizer_runs = 1000

ignored_error_codes = [2394]

[dependencies]
account-abstraction = { version = "0.7.0", url = "https://github.com/eth-infinitism/account-abstraction.git" }
openzeppelin-contracts = { version = "5.0.2", url = "https://github.com/OpenZeppelin/openzeppelin-contracts.git" }

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"
optimism_sepolia = "https://sepolia.optimism.io"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }